### PR TITLE
Fixes for Details Image and Video components w/ using AssetRenditions

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Some more unit tests - hopefully these are a good template for tests for the other details components

### CODE REVIEW

**Comment by godanny86** [comment]
@davidjgonzalez looks good. can you also update the legacy mode logic in `com.adobe.aem.commons.assetshare.components.details.impl.VideoImpl.java`?

**Comment by davidjgonzalez** [comment]
i assume this is what you meant: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/423/commits/ff417d0fc2e1bd48bdaa0dffac12347656fd2dda

**Comment by davidjgonzalez** [comment]
Weird - that should be the method now? 🤔... maybe the merge got messed up. Will try to look at it later today

**Comment by godanny86** [comment]
hmm @davidjgonzalez? are you referring to the comments I had on the PR? sorry I didn't resolve them... PR looks good to me though...

**Comment by davidjgonzalez** [comment]
@godanny86 oh - maybe looking on my phone confused me as to what change was what.

**Comment by godanny86** [comment]
@davidjgonzalez yeah I think it was just an old comment I left a few days ago. Going to start prepping for the release. Going with 1.8.0

**Comment by davidjgonzalez** [comment]
@godanny86 ah yeh - lol - i cant even find that comment now on GH; just in my email .. no idea :)

**Pull request merged**
