### PR TITLE
#472 - Fixed issue with InternalRedirectRenditionDispatcherImpl faili…

### PR DESCRIPTION
**Pull request by davidjgonzalez**
…ng to dispatch when /etc/map is configured

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@shajiahmed Any chance you could try this out w/ your /etc/map? It should fix #472

[asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4040840/asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip)

**Comment by shajiahmed** [comment]
@davidjgonzalez 
I tried the package, still it is not showing me the images,  I do see the following debug statements(no errors)

09.01.2020 11:39:05.176 *DEBUG* [0:0:0:0:0:0:0:1 [1578587945173] GET /content/dam/asset-share-commons/en/public/pictures/patrick-tomasso-199356.jpg.renditions/card/asset.rendition HTTP/1.1] com.adobe.aem.commons.assetshare.content.renditions.impl.dispatchers.InternalRedirectRenditionDispatcherImpl Serving internal redirect rendition [ /content/dam/asset-share-commons/en/public/pictures/patrick-tomasso-199356.jpg.thumb.319.319.jpg ~= http://aem-dispatcher-dev.cedars-sinai.org/content/dam/asset-share-commons/en/public/pictures/patrick-tomasso-199356.jpg.thumb.319.319jpg null] for resolved rendition name [ card ]
it seems that lines 123
pathInfo.getResourcePath() + pathInfo.getSelectorString() + pathInfo.getExtension() + pathInfo.getSuffix()
is just getting the resource path and extension
http://aem-dispatcher-dev.cedars-sinai.org/content/dam/asset-share-commons/en/public/pictures/patrick-tomasso-199356.jpg.thumb.319.319jpg null
there is a null appended for getSuffix
If I look at the html here is what I see generated tag in browser


I am not sure whether it has anything to do with /etc/map I am attaching the package here
[etcmap-1.0.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4041608/etcmap-1.0.zip)
Screen Shot 2020-01-09 at 12 09 11 PM

**Comment by davidjgonzalez** [comment]
@shajiahmed agh - i messed up the build - sorry; can you try this?

[asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4041767/asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip)

**Comment by shajiahmed** [comment]
Still the same issue
9.319.jpg ] for resolved rendition name [ card ]
09.01.2020 13:55:03.785 *DEBUG* [0:0:0:0:0:0:0:1 [1578596103769] GET /content/dam/asset-share-commons/en/public/pictures/adam-birkett-195692.jpg.renditions/card/asset.rendition HTTP/1.1] com.adobe.aem.commons.assetshare.content.renditions.impl.dispatchers.InternalRedirectRenditionDispatcherImpl Serving internal redirect rendition [ /content/dam/asset-share-commons/en/public/pictures/adam-birkett-195692.jpg.thumb.319.319.jpg ] for resolved rendition name [ card ]
`<a class="cmp-card__link" href="/content/asset-share-commons/en/cedars/details/image.html/content/dam/asset-share-commons/en/public/pictures/patrick-tomasso-199356.jpg">
            
        </a>`

Screen Shot 2020-01-09 at 1 57 10 PM

**Comment by davidjgonzalez** [comment]
Weird... you should be seeing a DEBUG that looks like 

```
log.debug("Serving internal redirect rendition [ {} ] for expression [ {} ] and resolved rendition name [ {} ]",
                    resourcePath,
                    evaluatedExpression,
                    parameters.getRenditionName());
```

IN the latest build... let me do one more build of the package (incase it was pulling the old bundle or something)... i tested the following on my local AEM and see:

```
09.01.2020 14:13:10.470 *DEBUG* [0:0:0:0:0:0:0:1 [1578597190466] GET /content/dam/asset-share-commons/en/public/pictures/florian-klauer-14840.jpg.renditions/card/asset.rendition HTTP/1.1] com.adobe.aem.commons.assetshare.content.renditions.impl.dispatchers.InternalRedirectRenditionDispatcherImpl Serving internal redirect rendition [ /content/dam/asset-share-commons/en/public/pictures/florian-klauer-14840.jpg ] for expression [ /content/dam/asset-share-commons/en/public/pictures/florian-klauer-14840.jpg.thumb.319.319.jpg ] and resolved rendition name [ card ]
```

[asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4042045/asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip)

**Comment by shajiahmed** [comment]
This package works fine I can see images now. Thank you

**Comment by davidjgonzalez** [comment]
@shajiahmed thanks for checking! sorry for the back and forth!

**Comment by shajiahmed** [comment]
I found one more issue, it works fine in author and preview mode when I view the page as published it throws error with status 500. 
 Operands are not of the same type: the equality operator can only be applied to String, Number and Boolean types.
seems to be coming from
apps.core.wcm.components.page.v1.page
Stack trace show me the following
10.01.2020 11:28:51.438 *ERROR* [0:0:0:0:0:0:0:1 [1578673731352] GET /content/asset-share-commons/en/cedars.html HTTP/1.1] org.apache.sling.engine.impl.SlingRequestProcessorImpl service: Uncaught SlingException
org.apache.sling.scripting.sightly.SightlyException: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: Operands are not of the same type: the equality operator can only be applied to String, Number and Boolean types.
        at com.adobe.cq.sightly.WCMScriptHelper.includeScript(WCMScriptHelper.java:227) [com.adobe.cq.sightly.cq-wcm-sightly-extension:1.6.0]
        at com.adobe.cq.sightly.internal.extensions.IncludeExtension.call(IncludeExtension.java:72) [com.adobe.cq.sightly.cq-wcm-sightly-extension:1.6.0]
        at org.apache.sling.scripting.sightly.impl.engine.runtime.RenderContextImpl.call(RenderContextImpl.java:77) [org.apache.sling.scripting.sightly:1.1.2.1_4_0]
        at org.apache.sling.scripting.sightly.apps.core.wcm.components.page.v1.page.page_html.render(page_html.java:83)
        at org.apache.sling.scripting.sightly.render.RenderUnit.render(RenderUnit.java:50) [org.apache.sling.scripting.sightly.runtime:1.1.0.1_4_0]
        at org.apache.sling.scripting.sightly.impl.engine.SightlyCompiledScript.eval(SightlyCompiledScript.java:60) [org.apache.sling.scripting.sightly:1.1.2.1_4_0]
        at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:386) [org.apache.sling.scripting.core:2.0.56]
        at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:184) [org.apache.sling.scripting.core:2.0.56]
        at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:491) [org.apache.sling.scripting.core:2.0.56]

**Comment by davidjgonzalez** [comment]
@shajiahmed hmm - can you provide the RequestProgress for this request? I cant tell at which script include this is failing. You can easily get RequestProgress for the request using:

https://chrome.google.com/webstore/detail/aem-chrome-plug-in/ejdcnikffjleeffpigekhccpepplaode?hl=en-US

..or if there are other logs that might indicate which ASC script being included is causing the problem.

Also, can you provide the version of AEM and ASC youre running? Thanks!

**Comment by shajiahmed** [comment]
Since the page is showing 500 error, there are not requestprogress logs are created in disabled mode.
I do see logs in preview and edit mode which is status code 200. I am attaching error logs and asset share logs, enabled debugger log for asset share package
I do see stack trace pointing to
```
Caused by: org.apache.sling.scripting.sightly.compiler.SightlyCompilerException: Operands are not of the same type: the equality operator can only be applied to String, Number and Boolean types.
        at org.apache.sling.scripting.sightly.compiler.expression.nodes.BinaryOperator.strictEq(BinaryOperator.java:247) [org.apache.sling.scripting.sightly.compiler:1.1.2.1_4_0]
        at org.apache.sling.scripting.sightly.apps.asset__002d__share__002d__commons.components.search.filter__002d__toggle.filter__002d__toggle_html.render(filter__002d__toggle_html.java:58)
```
[asset-share-commons.log](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4047874/asset-share-commons.log)

**Comment by davidjgonzalez** [comment]
@shajiahmed ahh! super - very helpful! ill take a look

**Comment by davidjgonzalez** [comment]
I think this was actually fixed in https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/464/files#diff-b354f1e82c63bf2dd2fa7a6aa7539359R25 which is in develop... i merged develop into this branch and rebuilt. Cant you test the package below? Below should be in sync with Develop plus the fix for the /etc/map with InternalRedirectRenditionDispatcher.

[asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/4049856/asset-share-commons.ui.apps-1.8.1-SNAPSHOT.zip)

**Comment by shajiahmed** [comment]
@davidjgonzalez 
I applied new package to environment, it works fine now in dispatcher and published mode.

Thanks for looking into this

**Pull request merged**
