### PR TITLE
Feature/317 dedicated fed

### PR DESCRIPTION
**Pull request by godanny86**

### CODE REVIEW

**Comment by godanny86** [comment]
Initial commit. So far only the Semantic UI Light theme has been re-organized into a dedicated module `ui.frontend.light`. Left the dark theme as is. Was planning on re-organizing the dark theme into a second dedicated module `ui.frontend.dark` but wanted to get some feedback @davidjgonzalez

**Comment by godanny86** [comment]
sorry another incredibly large PR

**Comment by davidjgonzalez** [comment]
@godanny86 im getting node build errors which appear to be stemming form ny version of node (v13.2.0) and the gulp 3.x

```
const { Math, Object } = primordials;
```

Sounds like you each have to drop to a lower version of node, or update gulp to 4.x (which requires updates to gulpfile). 

What's your build setup? It would be nice if we could use the latest stuff (gulp4 and latest node) -- but not sure if there are broader semantic-ui incompatibilities w/ that?

Also, can we do something like point the source definitions to the node-modoles/semnatic-ui/src/definitions folder to help limit the big "copy-down" of semantic-ui src into the project?

**Comment by godanny86** [comment]
@davidjgonzalez I experimented by switching over to Fomantic-UI. It is a community fork but seems to be more regularly updated: https://fomantic-ui.com/introduction/getting-started.html. Allows us to use the latest Gulp and node versions and there is actually new features.

I'm also excited to try: https://fomantic-ui.com/introduction/new.html#dynamic-less-compilation in the hope we can slim down our compiled CSS significantly....

I also removed `src/definitions`, `tasks/` and all themes except ASC Light from source control. The Fomantic UI should re-create those on install... Check it out!

**Comment by godanny86** [comment]
@davidjgonzalez re-did the PR using webpack approach, see PR #492

**Pull request closed without merging**
