### PR TITLE
Feature/223 thumbnail servlet

### PR DESCRIPTION
**Pull request by kaushalmall**
@davidjgonzalez submitting PR even though its not quite ready, but wanted to get your thoughts on the general idea here. 

Also, is there a way in the ThumbnailServletImpl class to return 319x319 (search results component) or the 1280x1280 (details page) thumbnail URL. That ways, this can be configured in either place and will work. 

Thoughts?

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@kaushalmall i was thinking it could be even simpler..

(this assumes the 319 thumb rendition is what we'll use to drive the thumbs)

1. Modify the existing Computed Property for ThumbnailImpl to do something like this...

```
if (asset has 319 thumbnail) {
     // Show asset's real thumbnail
     return asset.path + thumb servlet extension.
} else if (osgi.config has placeholder image path) {
    // Show custom placeholder
    return placeholder image path.
} else {
     // Show OOTB placeholder
     return asset.path + thumb servlet extension;
}
```

Of course the checks and resolutions are simplified...  but seems reasonable. I don't really see ppl changing out the missing placeholder regularly (likely with new Design > CSS deployments; ie Code deployments)

We could then remove the field from Page Properties, and make this noted in the Important Upgrade Considerations for this version.

If we REALLY want to make it naturally backwards compat, we could so something with Config/ SearchConfig to get any previously set value and use that if the osgi config placeholder doesnt exist.

**Comment by davidjgonzalez** [comment]
Wrt to the different sizes... ive been thinking we should add an extension (convention) to computed proprerties... so you could do something like

`data-sly-use.prop=asset.properties['thumbnail/large']` ... basically create convention to parameterize calls ...

I havent given it too much thought but i think we'd have to make sure:

1) The value caching is handled
2) Determine if the parameter selects a different ComputedProperty or its an actual parameter to a single ComputedProperty Impl (probably the latter)
3) How many params are allowed? I'd think 0 or many ... `data-sly-use.prop=asset.properties['thumbnail/large/png']` 
4) A different param convention? `data-sly-use.prop=asset.properties['thumbnail?size=large&format=png']`

**Comment by davidjgonzalez** [comment]
Also, naming a computed property "ThumbnailServlet" is kind of weird :) ... since that implies its a servlet, when it really just returns a path/URL to a resource that will rendition the Thumbnail (which happens to be a servlet, but thats sort of irrelevant... in theory it could point to a 3rd party system that is PHP or something :))

**Comment by kaushalmall** [comment]
@davidjgonzalez 
> I don't really see ppl changing out the missing placeholder regularly (likely with new Design > CSS deployments; ie Code deployments)

But, its really not a dev configuration. IMO, this should be a page property, even if this doesn't get changed often, seems out of place as an OSGi config. 

I can move it if you want, just LMK. 

WRT to changing the Computed Properties, I am still unclear on how those exactly work currently, will ping you directly for help there. 

And, yes, the class is named weird, but didn't want to care about that since I knew this was too complicated and wanted to get thoughts on what to do before spending too much time.

**Comment by badvision** [comment]
FWIW there is a asset thumbnail repair tool in MCP Tools which can help out, especially if folders have missing/incorrect thumbnails.

**Pull request closed without merging**
