### PR TITLE
Fix for Reference Asset By Asset ID on Publisher

### PR DESCRIPTION
**Pull request by vinaykhurana**
This PR is to resolve the issue #287 . Handled the use-case of "Enabling Asset referenced by Asset ID".

/cc : @kaushalmall

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
Hi @vinaykhurana  can you use the AssetResolver and avoid duplicating that logic?

I think we just have to  update that to 

```
@Reference
AssetResolver assetResolver;
...
return  assetResolver.resolveAsset(request) == null;
```

https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/content/impl/AssetResolverImpl.java#L42

**Comment by davidjgonzalez** [comment]
@kaushalmall  - yup ... and including @vinaykhurana's concern around the exception (which i forgot about)...

```
if (WCMMode.DISABLED.equals(wcmMode)) {       
	try {
		return assetResolver.resolveAsset( request ) == null;        
	}  catch(IllegalArguementException e) {
		return true;
	}
}

return false;
```

Of course its better to not use exceptions as code-flow-control, but in this case the alternative is much less elegant, and it's already in a conceptual "erroring" context.

**Comment by vinaykhurana** [comment]
@kaushalmall My concern was on the exception which AssetResolver.resolveAsset(.) throws if it is not able to resolve suffix path or ID to an asset. I think instead of throwing the IllegalArgumentException in AssetResolver, it should let the caller decide what to do if not able to resolve to an asset. Nevermind, i have updated the code as recommended by @davidjgonzalez . Please review.

**Comment by davidjgonzalez** [comment]
@vinaykhurana FWIW generally i agree with you, but since is a published public API, it's hard to change though without accidently affecting others! :T

**Comment by davidjgonzalez** [comment]
Thanks @vinaykhurana !

**Pull request merged**
