### PR TITLE
Feature/547 548

### PR DESCRIPTION
**Pull request by gkolluri**
Added Async download support to ASC. 

Contents:
1. Added async download component
2. Added Download component 
3. ContentHub support to downloads 
4. Skip download options modal - (configure in page properties)
5. Messages: Archive added to downloads panel
6. Setup and configure: MimeTypes for Async download service (OSGI)

Pending items:
1. Compatibility with AEM 6.5.x

Note: Will provide a separate content package for the async downloads default setup.

### CODE REVIEW

**Comment by gkolluri** [comment]
[async-downloads-content-2.0.zip](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/6032334/async-downloads-content-2.0.zip)

@davidjgonzalez please use the attached content package for initial setup.

**Comment by kaushalmall** [comment]
@gkolluri you should break this into smaller PRs, this PR has 60+ files, not a good way for someone to review. Please close this and open a PR per "feature"

**Comment by gkolluri** [comment]
Sure, I will open individual PRs. Closing this.

**Comment by davidjgonzalez** [comment]
@gkolluri if its not too much trouble - can you do a bulk format on the changed files (atleast the Java files) -- i was taking a spin through this trying to wrap my head around it, and bad indentation was making it hard to read -> understand. thanks!

**Pull request closed without merging**
