### PR TITLE
#27 - XSS Protected user provided data passed to the Email Share serv…

### PR DESCRIPTION
**Pull request by davidjgonzalez**
…ice.

Using XSSAPI to protect user provided data.

/cc @joerghoh - WDYT?

### CODE REVIEW

**Comment by joerghoh** [comment]
Hm, interesting question.

If we assume, that the email is actually an HTML email, the encoding is ok. But if it's just plain text, we have plain text with HTML encoded entities.

Maybe we should try to solve it on the email side, and create a "plain text email body" and "html email body" (of course you can combine into a single email as multi-part elements); and then we can do the encoding only for the HTML.

So I am not really convinced that here it's the right point. That's also the reason why I was hesitating to propose a patch.

**Comment by davidjgonzalez** [comment]
Some general thoughts:

* we use acs commons email api
* certain template parameters passed should be HTML, others as you rightly point out should not
* the email service should be decoupled from the origin invocation (ex maybe someone wants to have a Wf kick off an email that shares things)
* in the context of ASC share is there a reasonable use case for NOT having an HTML email?  the entire point of this service is to easily share assets from AEM; which in the world of the web (which is where ASC Resides) is HTML hyperlinks. I can’t think of a time when it’s be useful to share using plaintext emails?

**Comment by davidjgonzalez** [comment]
@joerghoh WDYT?

**Comment by joerghoh** [comment]
Regarding email: I still read my personal emails with mutt, preferring plain text :-)

But decoupling the sharing from sending an email would be great; I wouldn't prefer workflows (WFs on publish? Would like to avoid that as good as possible), but an intermediate service would be ok. I would see the task to properly escape data on the consuming part of this service.

**Comment by davidjgonzalez** [comment]
@joerghoh in a way the decoupling exists today, the ShareServlet [0] uses the high ranking ShareService implementation (Ex. Maybe you want to share over Slack!) 

Currently the only ShareService implementation is EmailShareServiceImpl [1] which uses the request submission params modeled by EmailShareImpl [3] to expose the Component + Request params.

The EmailShareImpl is ~ coupled with our stock Share Modal Component. Since we always envisioned HTML emails; we even in [1] compose a <ul> of hyperlinks that are passed to the email template for (albeit optional) use.

I think there are 3 sane/non-disruptive choices here:

1) Keep as is w the PR (blindly XSS all user input), and just imply the EmailShareService "means" HtmlEmailShareService.
2) Keep the PR as is, but rename EmailShareServiceImpl -> HtmlEmailShareServiceImpl to be abundantly clear its intended for HTML emails; and make a  strong note in the docs.
3) Add some sort of white list of user-provided property names that are exempt from XSS encoding (i think it should be default on).
4. Cant think of more :)
 
TBH, while i know you appreciate the mutt/pine/lynx and its ilk, i don't think AEM customers receiving these emails do; I can all but guarantee 100% of users will want HTML emails for the sharing use case, so i vote #1 since its simple and least change. #1 would still let your roll your own plaintext email share service.

[0] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/ShareServlet.java
[1] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareServiceImpl.java
[3] https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/components/actions/share/impl/EmailShareImpl.java

**Comment by joerghoh** [comment]
I am fine with the HTML stuff by default. I just would move the XSS escaping into the ShareService implementation.

**Pull request closed without merging**
