### PR TITLE
307/308 - Handle displaying images for non-image assets better

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Helps resolve issues described in #307/#308 where image previews/thumbnails are broken for unsupported (by the browser)(sometimes image) file formats.
/cc @HitmanInWis

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@HitmanInWis this look generally OK? I think ultimately we gotta fallback on the front-end, but its good to do some more checking on the backend as well.

**Comment by HitmanInWis** [comment]
Yes I agree with this @davidjgonzalez.  In my cursory testing it seems to be working well for the cases I outlined in #307 and #308

**Comment by godanny86** [comment]
btw I think the fix is easy enough for the cart if following the same approach as search results:
Update

`src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/_cq_dialog/.content.xml`

```diff
+  <missing-image
            jcr:primaryType="nt:unstructured"
           sling:resourceType="granite/ui/components/coral/foundation/form/pathfield"
           fieldLabel="Missing Image"
           fieldDescription="Image to use if no asset thumbnail can be found."
           filter="hierarchy"
           rootPath="/"
           name="./missingImage"/>
```
update: ` src/main/content/jcr_root/apps/asset-share-commons/components/modals/cart/cart.html`

```diff
     <td class="image">
+  <img src="${asset.properties['thumbnail'] || properties['missingImage'] @ context = 'attribute'}"
+         alt="${asset.properties['title']}"/>
-  <img src="${asset.properties['thumbnail']}" alt="${asset.properties['title']}"/>
</td>
```

image

**Comment by davidjgonzalez** [comment]
@godanny86 I made an adjustment to SearchConfigImpl so its better at resolving the Search Config even outside of the Search page itself - and leverage the missing image from that, so authors don't have to configure it 2x.

**Pull request merged**
